### ISSUE TITLE
jester/jester.lua is missing

### ISSUE THREAD

**Issue by andvaranaut** [thehunmonkgroup/jester#2]
Hi,

After cloning the current master branch and following the install instructions, I have noticed that the entrypoint (jester/jester.lua) is missing from the codebase. 

However, the instructions have not been updated accordingly, nor there seems to be another obvious entrypoint in the new codebase (my experience with Lua is very limited, though).

I'm guessing that either the file has to be recreated, possibly with any updates needed for the 2.x branch, or the usage instructions have to be updated. (As can be expected, when running 'lua jester/jester.lua' from fs_cli, FreeSwitch complains that the file can not be found). 

Any pointers are appreciated :) Thanks in advance for your help!

PS: The last commit in which jester.lua appears is c0f3d6cde470807631c94a8b52d7df59576e7d71 . As a workaround I have recovered the file from that commit (still testing whether it works, but at least it does not complain that the file does not exist), but that might very well be a very stupid idea :o)

**Comment by thehunmonkgroup** [comment]
Master/2.x is under heavy development, and not guaranteed to work.

1.x is a legacy branch that should work, but it not supported: https://github.com/thehunmonkgroup/jester/tree/v1.x#deprecated-branch----1x

Please take note of the deprecation warning.

**Comment by andvaranaut** [comment]
Many thanks for your reply, I'll keep experimenting.

I would suggest adding a note to that effect to the documentation, at least to 01-Intro.md.

Best
Jose

**Comment by thehunmonkgroup** [comment]
Fixed, added to 2.x README, and current doc. thx!
